# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20190124_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='view',
            new_name='views',
        ),
    ]
